version: '2.2'
services:
  apm-server:
    container_name: apmserver
    image: docker.elastic.co/apm/apm-server:7.10.0
    depends_on:
      elasticsearch:
        condition: service_healthy
      kibana:
        condition: service_healthy
    ports:
      - 8700:8700
    volumes:
      - ./apm-server.yml:/usr/share/apm-server/apm-server.yml
      - ${PWD}/apm_cert:/usr/share/apm-server/data
    healthcheck:
      interval: 10s
      retries: 12
      test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:8200/

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      #      - /srv/docker/es:/usr/share/elasticsearch/data
      - ${PWD}/es-data:/usr/share/elasticsearch/data
    expose:
      - 9200
    ports:
      - 9200:9200
    healthcheck:
      interval: 20s
      retries: 10
      test: curl -s http://localhost:9200/_cluster/health | grep -vq '"status":"red"'

  kibana:
    image: 'docker.elastic.co/kibana/kibana:7.10.0'
    container_name: kibana
    volumes:
      - ./kibana.yml:/Users/Shared/kibana/config/kibana.yml
    depends_on:
      elasticsearch:
        condition: service_healthy
    environment:
      SERVER_NAME: kibana.local
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
      - '5601:5601'
    healthcheck:
      interval: 10s
      retries: 20
      test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:5601/api/status
